channels:
  - conda-forge
  - defaults
dependencies:
  - cairo=1.16.0
  - python=3.8.8
  - sqlite=3.35.4
  - pip>=21.0.1
  - pip:
    - matplotlib==3.3.2
    - pandas==1.2.3
    - ipywidgets==7.5.1
    - pydantic==1.9.1
    - rdkit>=2020.09.1
    - rxnmapper==0.1.2
    - cairosvg==2.4.2
    - modin==0.9.1
    - chempy==0.7.12
    - numpy==1.19.2
    - ray==1.1.0
    - cirpy==1.0.2
    - typing_extensions==4.3.0
    - pillow==7.2.0
    - grpcio-status==1.33.2
    - protobuf==3.19.6
    - ttictoc==0.5.6
    - lxml==4.6.2
    - jupyterlab==4.0.0
    - dask[dataframe]==2.19.0
    - dask[distributed]==2.19.0